### ISSUE TITLE
PreRendering時に/posts/[id].tsxの`TagsLayout`の`key`がundefinedでエラー

### ISSUE THREAD

**Issue by shzawa** [tk-ozawa/nextjs-blog-from-scratch#3]
## 状況

`npm run dev`実行後 http://localhost:3000 にアクセスすると以下のようなエラー

```zsh
→ npm run dev

> nextjs-blog@0.1.0 dev /Users/ozawa_shotaro/sandbox/nextjs-blog
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - compiled successfully
Warning: TagsLayout: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
    at TagsLayout (webpack-internal:///./components/layout.tsx:132:20)
    at li
    at ul
    at section
    at main
    at div
    at Container (webpack-internal:///./components/layout.tsx:24:19)
    at HomeLayout (webpack-internal:///./components/layout.tsx:59:20)
    at HomePage (webpack-internal:///./pages/index.tsx:34:18)
    at MyApp (webpack-internal:///./pages/_app.tsx:24:15)
    at AppContainer (/Users/ozawa_shotaro/sandbox/nextjs-blog/node_modules/next/dist/next-server/server/render.js:28:950)
```

## 分かっていること

- PreRendering時には`TagsLayout`内の`li`タグの`key`が空
  - `key`が空の時空文字を挿入 -> 効果なし

**Comment by shzawa** [comment]
`key={id ?? 'hoge'}`って入れた結果がこちら↓

```zsh
$ npm run dev
> nextjs-blog@0.1.0 dev /Users/ozawa_shotaro/sandbox/nextjs-blog
> next dev

ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Using webpack 4. Reason: custom webpack configuration in next.config.js https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /
wait  - compiling...
event - build page: /404
Warning: TagsLayout: `key` is not a prop. Trying to access it will result in `undefined` being returned. If you need to access the same value within the child component, you should pass it as a different prop. (https://reactjs.org/link/special-props)
    at TagsLayout (webpack-internal:///./components/layout.tsx:122:20)
    at li
    at ul
    at section
    at main
    at div
    at Container (webpack-internal:///./components/layout.tsx:24:19)
    at HomeLayout (webpack-internal:///./components/layout.tsx:55:20)
    at HomePage (webpack-internal:///./pages/index.tsx:34:18)
    at MyApp (webpack-internal:///./pages/_app.tsx:24:15)
    at AppContainer (/Users/ozawa_shotaro/sandbox/nextjs-blog/node_modules/next/dist/next-server/server/render.js:28:950)
```
